config/routes.rb
Blogotron::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :users, :only => [:index] do
    resources :posts, :only => [:index]
  end
  
  resources :posts do
    resources :comments, :only => [:create]
  end
  resources :comments, :only => [:update, :destroy]
  
  match 'blogs/:user_id' => 'posts#index', :as => :blogs
  
  root :to => 'posts#index'
end

app/models/comment.rb
# encoding: utf-8
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  validates :content, :presence => true
end

app/models/post.rb
# encoding: utf-8
class Post < ActiveRecord::Base
  attr_accessible :subject, :content, :user
  
  belongs_to :user
  has_many :comments, :dependent => :destroy
  
  validates :subject, :presence => {:message => "не может быть пустой"}
  validates :content, :presence => true
  
  scope :ordered, :order => "updated_at DESC"
end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :login, :avatar, :avatar_cache, :remove_avatar
  
  # Связи
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
# encoding: utf-8

class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_comment, :only => [:update, :destroy]

  def create
    @post = current_user.posts.find(params[:post_id])
    
    @comment = @post.comments.new(params[:comment])
    @comment.user = current_user
    
    if @comment.save
      redirect_to @post, :notice => "Комментарий успешно создан."
    else
      redirect_to @post, :alert => "Проблема при создании комментария: " + @comment.errors.messages[:content].first.to_s
    end
  end

  def update
    if @comment.update_attributes(params[:comment])
      redirect_to :back, :notice => "Комментарий был успешно обновлен"
    else
      redirect_to :back, :notice => "При удалении комментария возникла проблема"
    end
  end

  def destroy
    @comment.destroy
    redirect_to :back, :notice => "Ваш комментарий был успешно удален."
  end

  private
    def find_comment
      @comment = current_user.comments.find(params[:id])
    end

end

app/controllers/posts_controller.rb
# encoding: utf-8

class PostsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :find_and_check_post_owner, :only => [:update, :destroy]
  
  def index
    @user = User.find(params[:user_id]) unless params[:user_id].blank?
    # @user не пустая, значит запросили /users/:id/posts. Нет - значит запросили /posts
    @user ? @posts = Post.where("user_id = #{@user.id}").ordered : @posts = Post.ordered
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(params[:post])
    if @post.save
      redirect_to @post, :notice => "Запись успешно создана."
    else
      render :action => 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to root_path, :alert => "Только автор может редактировать свои записи" unless @post.user == current_user
  end

  def update
    if @post.update_attributes(params[:post])
      redirect_to @post, :notice  => "Запись успешно обновлена."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, :notice => "Запись успешно удалена."
  end
  
  private
  def find_and_check_post_owner
    @post = current_user.posts.find(params[:id])
    redirect_to root_path, :alert => "Только автор может управлять своими записями" unless @post.user == current_user
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def update
      # Override Devise to use update_attributes instead of update_with_password.
      # This is the only change we make.
      if resource.update_attributes(params[resource_name])
        set_flash_message :notice, :updated
        # Line below required if using Devise >= 1.2.0
        sign_in resource_name, resource, :bypass => true
        redirect_to after_update_path_for(resource)
      else
        clean_up_passwords(resource)
        render_with_scope :edit
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/comments/_comment.html.haml
.comments
  .comment-header
    - unless comment.user.avatar.blank?
      = image_tag comment.user.avatar
    - else
      =image_tag "noavatar.png"

    = link_to comment.user.email, blogs_url(comment.user)
    %br/
    %span.date= comment.updated_at.strftime("%d.%m.%Y %H:%M:%S")
  %p= comment.content
  - if current_user == comment.user
    = link_to "Удалить комментарий", comment, :confirm => 'Вы уверены?', :method => :delete

app/views/comments/_form.html.haml
= form_for([@post, @post.comments.build]) do |f|
  = f.error_messages
  %p
    = f.label :content, "Комментарий"
    %br/
    = f.text_area :content
  %p
    = f.submit "Создать комментарий"

app/views/layouts/_header.html.haml
.header
  .feed
    = link_to "Лента последних записей", root_path
  .login_items
    %ul
      - if user_signed_in?
        %li
          Зашли как: #{current_user.email}
        %li
          |
        %li
          = link_to "Профиль", edit_user_registration_path
        %li
          |
        %li
          = link_to "Мой блог", blogs_url(current_user)
        %li
          |
        %li
          = link_to "Выйти", destroy_user_session_path, :method => :delete
      - else
        %li
          = link_to "Войти", new_user_session_path
        %li
          |
        %li
          = link_to "Зарегистрироваться", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      = render :partial => 'layouts/header'
      
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
      = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  = f.error_messages :header_message => "Создать новую запись не удалось", :message => "Необходимо исправить следующие ошибки:"
  %p
    = f.label :subject, "Тема записи"
    %br/
    = f.text_field :subject
  %p
    = f.label :content, "Содержимое"
    %br/
    = f.text_area :content
  %p= f.submit "Создать запись"

app/views/posts/edit.html.haml
- title current_user.email + " | Редактирование записи"
= render 'form'
%p
  = link_to "Показать", @post

app/views/posts/index.html.haml
-if @user
  - title "Все записи пользователя " + @user.email
  %h2
    Все записи пользователя: #{@user.email}
-else
  - title "Лента последних записей"
  %h2
    Лента последних записей
    
%p
  Всего #{@posts.count.to_s + " " + Russian.p(@posts.count, "запись", "записи", "записей")}.
%hr/
%br/
- for post in @posts
  .post_header
    .avatar
      - unless post.user.avatar.blank?
        = image_tag post.user.avatar
      - else
        =image_tag "noavatar.png"
    .params
      Пишет: #{link_to post.user.email, blogs_url(post.user)}
      %br/
      Дата: #{post.updated_at.strftime("%d.%m.%Y %H:%M:%S")}
  %h1= post.subject
  %p
    = post.content
  %p
  %p
    / Количество комментариев
    - if post.comments.count > 0
      = link_to post.comments.count.to_s + " " + Russian.p(post.comments.count,"Комментарий", "Комментария", "Комментариев"), post_path(post)
    - else
      = link_to "Нет комментариев", post_path(post)
    / Ссылка сразу на добавление комментария
    | #{link_to "Добавить комментарий", post_path(post) + "#add_comment"}
  - if (current_user == post.user)
    = link_to "Редактировать", edit_post_path(post)
    |
    = link_to "Удалить", post_path(post), :confirm => 'Вы уверены?', :method => :delete
  %hr/
  %br/
- if ((@user && current_user == @user) || (@user.blank? && signed_in?))
  %p= link_to "Создать новую запись", new_post_path

app/views/posts/new.html.haml
- title current_user.email + " | Создание новой записи"
= render 'form'
%p= link_to "Назад к списку записей", blogs_url(current_user)

app/views/posts/show.html.haml
- title @post.user.email + " | " + @post.subject
.post_header
  .avatar
    - unless @post.user.avatar.blank?
      = image_tag @post.user.avatar
    - else
      =image_tag "noavatar.png"
  .params
    Пишет:
    - if @post.user.blank? 
      "Неизвестен"
    - else
      = link_to @post.user.email, blogs_url(@post.user)
    %br/
    Дата: #{@post.updated_at.strftime("%d.%m.%Y %H:%M:%S")}
%h1= @post.subject
%p
  = @post.content
%p
  - if (current_user == @post.user)
    = link_to "Редактировать", edit_post_path(@post)
    |
    = link_to "Удалить", @post, :confirm => 'Вы уверены?', :method => :delete

- unless @post.comments.blank?
  = render @post.comments
  
%a{:name => "add_comment"}
- if signed_in?
  = render "comments/form"
- else
  Только зарегистрированные пользователи могут оставлять комментарии
  %br/
  = link_to "Войти", new_user_session_path
  или
  = link_to "Зарегистрироваться", new_user_registration_path    

app/views/users/index.html.haml
%h1 Список всех пользователей в системе

- @users.each do |user|
  %ul(style="font-weight: bold; list-style-type: none;")
    %li #{user.id}. #{link_to user.email, blogs_url(user)}